-d D:\project\Button_Counter_Display\impl\gwsynthesis\Button_Counter_Display.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\project\Button_Counter_Display\src\top.cst
-cfg D:\project\Button_Counter_Display\impl\pnr\device.cfg
-sdc D:\project\Button_Counter_Display\src\top.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
